import styled from 'styled-components';
import React from 'react';
import Journal from '../Journals.json';

const HomeDiv = styled.div`
  font-family: 'Roboto', sans-serif;
  margin: 20px;
  h1 {
    font-size: 50px;
    padding-top: 20px;
  }
  p {
    font-size: 20px;
  }
  table {
    margin: 40px;
    border-collapse: collapse;

    tr,
    td {
      border: 1px solid #dddddd;
      text-align: left;
      padding: 10px;
      margin: 10px;
    }
  }
`;

const FlexDiv = styled.div`
  display: flex;
  justify-content: space-between;
`;

const StyledJournalEntry = styled.div`
  box-shadow: ${props => props.theme.bs};
  border: 1px solid black;
  width: 30%;
  text-align: center;
`;

class Homepage extends React.Component {
  constructor(props) {
    super(props);
  }
  async componentDidMount() {}
  render() {
    return (
      <HomeDiv>
        <FlexDiv>
          <div>
            <h1>Hey Welcome to My Labs Blogs</h1>
            <p>
              My name is Carlo Clamucha and I'm currently working on the
              business reviews
            </p>
          </div>
          <div>
            <h1> User Schema</h1>
            <table>
              <tbody>
                <tr>
                  <th>id - autogenerated</th>
                  <th>name - required</th>
                  <th>email - required</th>
                  <th>password - required</th>
                  <th>gravatar - autogenerated</th>
                </tr>
                <tr>
                  <td>1</td>
                  <td>Carlo</td>
                  <td>carlo@carlo.com</td>
                  <td>123125wqegqs</td>
                  <td>http://gravatar/carlo?s=200</td>
                </tr>
              </tbody>
            </table>
          </div>
        </FlexDiv>
        <FlexDiv>
          {Journal.map(entry => {
            return (
              <StyledJournalEntry>
                <p> Day {entry.Day}</p>
                <p>{entry.Contributions}</p>
                <p>{entry.Description}</p>
                <p>{entry.frontEndLink}</p>
                <p>{entry.backEndLink}</p>
              </StyledJournalEntry>
            );
          })}
        </FlexDiv>
      </HomeDiv>
    );
  }
}

export default Homepage;
