import React, { Component } from 'react';
import Link from 'next/link';
import styled from 'styled-components';
const TableContainer = styled.div`
  width: 40%;
  margin: 0 auto;
  background-color: whitesmoke;
  table {
    border-collapse: collapse;
    tr,
    td {
      border: 1px solid #dddddd;
      text-align: left;
      padding: 1rem;
      margin: 1rem;
    }
  }
`;

export default class componentName extends Component {
  render() {
    return (
      <div>
        <TableContainer>
          <h1 className="table__heading">User Schema</h1>
          <table>
            <tbody>
              <tr>
                <th>id - autogenerated</th>
                <th>name - required</th>
                <th>email - required</th>
                <th>password - required</th>
                <th>gravatar - autogenerated</th>
              </tr>
              <tr>
                <td>1</td>
                <td>Carlo</td>
                <td>carlo@carlo.com</td>
                <td>123125wqegqs</td>
                <td>http://gravatar/carlo?s=200</td>
              </tr>
            </tbody>
          </table>
        </TableContainer>
      </div>
    );
  }
}
