import React, { Component } from 'react';
import styled from 'styled-components';
import weekly from '../Weekly.json';
import Link from 'next/link';
const HomeDiv = styled.div`
  font-family: 'Roboto', sans-serif;
  margin: 20px;
  h1 {
    font-size: 50px;
    padding-top: 20px;
  }
  p {
    font-size: 20px;
  }
  a {
    font-size: 20px;
  }
  table {
    margin: 40px;
    border-collapse: collapse;

    tr,
    td {
      border: 1px solid #dddddd;
      text-align: left;
      padding: 10px;
      margin: 10px;
    }
  }
`;

const WeeklyDiv = styled.div`
  border: 1px solid black;
  border-radius: 5px;
  width: 40%;
  text-align: center;
`;

export default class Weekly extends Component {
  componentDidMount() {}
  render() {
    return (
      <HomeDiv>
        <div>
          <table>
            <tbody>
              <tr>
                <th>id - autogenerated</th>
                <th>name - required</th>
                <th>email - required</th>
                <th>password - required</th>
                <th>gravatar - autogenerated</th>
              </tr>
              <tr>
                <td>1</td>
                <td>Carlo</td>
                <td>carlo@carlo.com</td>
                <td>123125wqegqs</td>
                <td>http://gravatar/carlo?s=200</td>
              </tr>
            </tbody>
          </table>
          <Link href="/">
            <a>Home</a>
          </Link>
        </div>
        <div>
          {weekly.map(week => {
            return (
              <WeeklyDiv>
                <p>Week {week.week}</p>
                <p>{week.weekly_journal}</p>
                <div>
                  <p>Tickets</p>
                  {week.tickets.map(ticket => {
                    return (
                      <div>
                        <p>{ticket.ticket}</p>
                      </div>
                    );
                  })}
                </div>
                {week.trello_card.map(card => {
                  return (
                    <div>
                      <a href={card.card}>{card.card}</a>
                    </div>
                  );
                })}
                {week.PRS.map(PR => {
                  return (
                    <div>
                      <a href={PR.prLink}>{PR.prLink}</a>
                    </div>
                  );
                })}
              </WeeklyDiv>
            );
          })}
        </div>
      </HomeDiv>
    );
  }
}
